CREATE DATABASE FUNDTRADER;

USE FUNDTRADER;

CREATE TABLE BANK (
	id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    PRIMARY KEY( id )
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE BANKACCOUNT (
	client_code INTEGER NOT NULL ,
    bank_code INTEGER NOT NULL,
    sort_code VARCHAR(6) NOT NULL,
    account_no VARCHAR(8) NOT NULL UNIQUE,
    PRIMARY KEY( client_code ),
    FOREIGN KEY( bank_code ) REFERENCES BANK(id)
) ENGINE=InnoDB;

CREATE TABLE CLIENTSTATUS (
	code INTEGER NOT NULL,
    narrative VARCHAR(40) NOT NULL,
    PRIMARY KEY( code )
) ENGINE=InnoDB;

CREATE TABLE TITLE (
	short VARCHAR(20) NOT NULL,
    full VARCHAR(60) NOT NULL UNIQUE,
    PRIMARY KEY( short )
) ENGINE=InnoDB;

CREATE TABLE CLIENT (
    code INTEGER NOT NULL AUTO_INCREMENT,
    surname VARCHAR(80) NOT NULL,
    forenames VARCHAR(120) NOT NULL,
    title VARCHAR(20),
    date_of_birth DATE,
    ni_number VARCHAR(9) NOT NULL UNIQUE,
    start_date DATE,
    end_date DATE,
    status_code INTEGER NOT NULL,
    aml_flag BOOLEAN,
    PRIMARY KEY( code ),
    FOREIGN KEY( title ) REFERENCES TITLE(short),
    FOREIGN KEY( status_code ) REFERENCES CLIENT_STATUS( code )
) ENGINE=InnoDB;

CREATE TABLE USER_STATUS (
	code INTEGER NOT NULL,
    narrative VARCHAR(40) NOT NULL,
    PRIMARY KEY( code )
) ENGINE=InnoDB;

CREATE TABLE USER (
	id INTEGER NOT NULL AUTO_INCREMENT,
    surname VARCHAR(80) NOT NULL,
    forename VARCHAR(120) NOT NULL,
    title VARCHAR(20) NOT NULL,
    login_name VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    status_code INTEGER NOT NULL,
    PRIMARY KEY( id ),
    FOREIGN KEY( title ) REFERENCES TITLE(short),
    FOREIGN KEY( status_code ) REFERENCES USER_STATUS( code )
) ENGINE=InnoDB;

CREATE TABLE AUDIT (
	id INTEGER NOT NULL AUTO_INCREMENT,
    table_name VARCHAR(60) NOT NULL,
    table_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    entry_date DATE NOT NULL,
    entry_time TIME NOT NULL,
    PRIMARY KEY( id ),
    FOREIGN KEY ( user_id ) REFERENCES USER( id )
) ENGINE=InnoDB;

CREATE TABLE TRADE_STATUS (
	code CHAR NOT NULL,
    narrative VARCHAR(40) NOT NULL,
    PRIMARY KEY( code )
) ENGINE=InnoDB;

CREATE TABLE TRADE_TYPE (
	code CHAR NOT NULL,
    narrative VARCHAR(40) NOT NULL,
    PRIMARY KEY( code )
) ENGINE=InnoDB;

CREATE TABLE TRADE_BASIS (
	code CHAR NOT NULL,
    narrative VARCHAR(40) NOT NULL,
    PRIMARY KEY( code )
) ENGINE=InnoDB;

CREATE TABLE FUND_STATUS (
	id INTEGER NOT NULL,
    narrative VARCHAR(40) NOT NULL,
    PRIMARY KEY( id )
) ENGINE=InnoDB;

CREATE TABLE FUND_MGR (
	code INTEGER NOT NULL,
    name VARCHAR(60) NOT NULL,
    PRIMARY KEY( code )
) ENGINE=InnoDB;

CREATE TABLE FUND (
	isin VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL UNIQUE,
    status INTEGER NOT NULL,
    price DECIMAL NOT NULL,
    fund_mgr_code INTEGER NOT NULL,
    PRIMARY KEY( isin ),
    FOREIGN KEY( status ) REFERENCES FUND_STATUS( id ),
    FOREIGN KEY( fund_mgr_code ) REFERENCES FUND_MGR( code )
) ENGINE=InnoDB;

CREATE TABLE CLIENT_TRADE (
	ref INTEGER NOT NULL AUTO_INCREMENT,
    client_code INTEGER NOT NULL,
    isin VARCHAR(30) NOT NULL,
    fund_mgr_code INTEGER NOT NULL,
    type CHAR NOT NULL,
    basis CHAR NOT NULL,
    units DECIMAL,
    price DECIMAL,
    value DECIMAL,
    status_code CHAR NOT NULL,
    contract_note_id INTEGER NOT NULL,
    PRIMARY KEY( ref ),
    FOREIGN KEY( client_code ) REFERENCES CLIENT( code ),
    FOREIGN KEY( isin ) REFERENCES FUND( isin ),
    FOREIGN KEY( fund_mgr_code ) REFERENCES FUND_MGR( code ),
    FOREIGN KEY( type ) REFERENCES TRADE_TYPE( code ),
    FOREIGN KEY( basis ) REFERENCES TRADE_BASIS( code ),
    FOREIGN KEY( status_code ) REFERENCES TRADE_STATUS( code )
) ENGINE=InnoDB;

CREATE TABLE CONTRACT_NOTE (
	id INTEGER NOT NULL AUTO_INCREMENT,
    client_trade_ref INTEGER NOT NULL,
    units DECIMAL NOT NULL,
    price DECIMAL NOT NULL,
    value DECIMAL NOT NULL,
    market_trade_date DATE NOT NULL,
    PRIMARY KEY( id ),
    FOREIGN KEY( client_trade_ref ) REFERENCES CLIENT_TRADE( ref )
) ENGINE=InnoDB;

CREATE TABLE DEALING_HISTORY (
	ref	INTEGER NOT NULL AUTO_INCREMENT,
    client_code INTEGER NOT NULL,
    isin VARCHAR(30) NOT NULL,
    tx_date DATE NOT NULL,
    type CHAR NOT NULL,
    basis CHAR NOT NULL,
    units DECIMAL NOT NULL,
    bookcost DECIMAL,
    proceeds DECIMAL,
    contract_note_id INTEGER,
    PRIMARY KEY( ref ),
    FOREIGN KEY( client_code ) REFERENCES CLIENT( code ),
    FOREIGN KEY( isin ) REFERENCES FUND( isin ),
    FOREIGN KEY( type ) REFERENCES TRADE_TYPE( code ),
    FOREIGN KEY( basis ) REFERENCES TRADE_BASIS( code ),
    FOREIGN KEY( contract_note_id ) REFERENCES CONTRACT_NOTE( id )
) ENGINE=InnoDB;


DROP TABLE DEALING_HISTORY;
DROP TABLE CONTRACT_NOTE;
DROP TABLE CLIENT_TRADE;
DROP TABLE FUND;
DROP TABLE FUND_MGR;
DROP TABLE FUND_STATUS;
DROP TABLE TRADE_BASIS;
DROP TABLE TRADE_TYPE;
DROP TABLE TRADE_STATUS;
DROP TABLE AUDIT;
DROP TABLE USER;
DROP TABLE USER_STATUS;
DROP TABLE CLIENT;
DROP TABLE TITLE;
DROP TABLE CLIENT_STATUS;
DROP TABLE BANK_ACCOUNT;
DROP TABLE BANK;


